version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Fetch Dependencies
          command: |
            echo "Fetch Dependencies"
            sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
            neofetch