version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Hello world
          command: |
            echo Hello 
            sudo apt install neofetch
            neofetch