version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu-2204:2022.04.1
    steps:
      - run:
          name: Hello world
          command: |
            echo Hello 
            apt install neofetch
            neofetch