version: 2.1
jobs:
  build:
    machine: # executor type
      image: ubuntu-2204:2022.04.2 # # recommended linux image - includes Ubuntu 
    steps:
      - run:
          name: Fetch Dependencies
          command: |
            echo "Fetch Dependencies"
            sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - run:
          name: Fetch repo tool
          command: |
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            mkdir crdroid
            cd crdroid
            repo init --depth=1 -u https://github.com/crdroidandroid/android.git -b 12.1
            repo sync -j8
